# Generated by Django 5.2.11 on 2026-02-23 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('interest_icon', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_text', models.CharField(max_length=255)),
                ('phrase_icon', models.CharField(max_length=255)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.interest')),
            ],
        ),
    ]
